### PR TITLE
Higher or original resolution artworks

### LINKED ISSUE #68: Locate and add available uncompressed PNG artwork
"Available" obviously means stuff that wasn't locked behind a paywall, but as we've discussed, that's basically all publicly visible artwork on any Bandcamp (`_0.png` suffix bcbits URLs), and whatever can be recovered from official releases, since all the official ways to buy their artwork have been taken offline.

Ties in with hsmusic/hsmusic-wiki#70 nicely - we should get these in the same update! (Not the one currently being finalized though.)

(We can break this issue into a todo checklist if we want to track progress granularly)

### PR DESCRIPTION
**Pull request by towerofnix**
Obviously most of the changes are in the corresponding hsmusic-media branch.

- **Official Discography:**
  - Albums below include artwork alongside MP3s/tracks in original Bandcamp downloads (still accessible from own purchases page)
  - [x] Cherubim
  - [x] Homestuck Vol. 8
  - [x] Homestuck Vol. 9
  - Some of these are jpeg's - sorry, either the export process for usage on Bandcamp / compilation in the album zip was kind of weird, or crazy high res art just wasn't the norm in 2012!!
  - Higher-resolution archive from Bandcamp (see below) - official artist contributions:
  - [x] Homestuck Vol. 7
  - [x] Homestuck Vol. 8
  - [x] Homestuck Vol. 9
  - [x] Homestuck Vol. 10
  - [x] coloUrs and mayhem: Universe A
  - [x] coloUrs and mayhem: Universe B
  - [x] The Wanderers
  - [x] Prospit & Derse
  - [x] One Year Older
  - [x] Genesis Frog
  - [x] Cherubim
  - [x] All album covers
  - Comic panels/crops:
  - [x] Homestuck Vol. 1-4, ~~1, 2, 3, 4~~ (these were removed long before the bcbits time and probably aren't accessible anymore)
  - [x] Homestuck Vol. 6
  - [x] [S] Collide.
  - [x] Act 7
  - [x] Midnight Crew: Drawing Dead
  - [x] The Felt
  - [x] Strife!
  - [x] Mobius Trip and Hadron Kaleido
  - [x] Alternia, AlterniaBound (alternate/original art)
  - [x] Hiveswap Friendsim
  - Anthology edits - these are probably PNG in the download:
  - [x] Homestuck Vol. 5
  - [x] Alternia
  - [x] AlterniaBound
  - [x] Beyond Canon
  - Originally we kept original-resolution art for official albums off the wiki as it could be considered "exclusive" to the album purchase - but artworks have been completely removed from the (not-so-) new "compilation" releases, including from the downloads, and all official Homestuck albums [with art] are *at least* 6 years old now, so there's very little argument against archiving and publicizing artist originals
  - For all albums with **public** track art (not bonus tracks), it's possible to access (what might be) original-res, uncompressed artwork assets directly from Bandcamp's bcbits.com URLs, which are still online even though the album and track pages themselves were unlisted (see https://github.com/hsmusic/hsmusic-data/pull/76#issuecomment-1372202491)
    > good news for fans of art: the image assets for the official discography on bandcamp are still online on bcbits.com, including the max [im pretty sure] as-uploaded resolution (which is also PNG if available) — obviously the track pages w/ art are all down, but you can locate the bcbit urls that still work through web.archive.org; then just replace the _10.jpg with _0.jpg for max res [which will still serve a png if available, even tho you typed jpg]
  - Some artists who contributed art to official albums may have uploaded higher-resolution art to tumblr or other sites; if these happen to still be around, it's worth investigating, but no granular todo's in this PR (currently)
- **UMSPAF:**
  - [x] [Ancestral](https://www.dropbox.com/s/8agx5jdyw1eeqoa/Ancestral%20Art.rar?dl=0r)
  - [x] [Beforus](https://www.dropbox.com/s/t28rxhb0ff658um/Beforus%20Track%20Art.zip?dl=0)
  - [x] [Bee-forus: Seatbelt Safebee](https://www.dropbox.com/s/a3xbswhkf41w04p/Seatbelt%20Safebee%20-%20track%20art.zip?dl=0)
  - [x] [Land of Fans and Music 2](http://cdn.skaia.net/music/artwork/lofam2_artwork.zip)
  - [x] [Land of Fans and Music 3](http://cdn.skaia.net/music/artwork/lofam3_artwork.zip)
  - [x] [Land of Fans and Music 4](https://www.dropbox.com/s/0s5szcyzm8khqsy/Lofam%204%20Art.rar?dl=0)
  - [x] [Weird Puzzle Tunes](https://www.dropbox.com/s/yqub1bg83o25g60/Art%20of%20the%20Project%20-%20WPT.zip?dl=0)
  - No art zip DLC for albums past LOFAM 4, inquire with UMSPAF management? (These can probably also be gotten with Bandcamp archive method described above)
    - [x] Cosmic Caretakers
    - [x] Diverging Delicacies
    - [x] FriendSymphony
    - [x] ~~Land of Fans and Music 5~~ (basically already done, thanks Niklink!)
    - [x] Moons of Theseus
    - [x] Xenoplanetarium
- Album covers: official discography
    - [x] Act 7, MC:DD, The Felt, Strife!, MT&HK, Alternia, AlterniaBound
    - [x] Vol. 1-4, 5, 6, Squiddles
    - [x] Vol. 7, 8, Sburb, Wanderers, Prospit & Derse, Song of Skaia
    - [x] Vol. 9, C&M A+B, Symphony Impossible to Play, One Year Older, Genesis Frog, Cherubim
    - [x] [S] Collide, Vol. 10, Grubbles, Hiveswap 1 & 2, Friendsim, Beyond Canon
- Album covers: UMSPAF
    - [x] LoFaM 2, 3, SBURB OST + DLC, Beforus + DLC, Weird Puzzle Tunes
    - [x] LoFaM 4, Vaporwave 2016, Ancestral, Xenoplanetarium, Gristmas Carols
    - [x] LoFaM 5, Cosmic Caretakers, Moons of Theseus, Diverging Delicacies, Friendsymphony
- Rest of Fandom + Beyond are for a follow-up update.

### CODE REVIEW

**Comment by Niklink** [comment]
[List of all official albums linked on Wayback Machine](https://www.one-tab.com/page/LNlSy3T_R8q-zigZpIGznQ)

Could you please elaborate on how you produce the correct 'modern' bcbits URLs? I tried doing exactly this in the past and I couldn't get it to work.

**Comment by towerofnix** [comment]
> Could you please elaborate on how you produce the correct 'modern' bcbits URLs? I tried doing exactly this in the past and I couldn't get it to work.

Sure, I had the thought earlier that it would be worth clarifying in the PR description too:

1. Locate an album or track page on web.archive.org, if it's unavailable on current Bandcamp. I'll use Unite Synchronization from Homestuck Vol. 8 as an example: http://web.archive.org/web/20160501032732/http://homestuck.bandcamp.com/album/homestuck-vol-8 http://web.archive.org/web/20160412210933/http://homestuck.bandcamp.com/track/unite-synchronization
2. Click the cover art. It will most likely bring you to a "we haven't archived that URL" type page, in which case the URL should be visible in the text box, or else in the Wayback Machine navigation bar. Navigating to the `bcbits.com` URL directly, you should still be able to access the original art as it would have been linked from the album/track page. http://f4.bcbits.com/img/a2681527627_10.jpg
3. Take the `_10.jpg` at the end of the URL and change it to `_0.jpg`. You can also change it to `_0.png`—this **will not alter** the file which bcbits.com serves you, so if it's internally stored as a PNG, you'll get a PNG file even if you have `.jpg` at the end. http://f4.bcbits.com/img/a2681527627_0.jpg
4. Download and compare files. Unite Synchronization (for example) is already served at its max resolution, 500x500 (`_10.jpg` URLs go up to 1200x1200 I think?), but with `_10.jpg` it's a JPEG image with clear compression around contrasting edges, and with `_0.jpg` (or `_0.png`) it's a PNG image with no artifacting.

Other examples:

- Ocean Stars Falling: [`_10.jpg`](http://f4.bcbits.com/img/a2163260441_10.jpg), 1200x1200 JPEG; [`_0.jpg`](http://f4.bcbits.com/img/a2163260441_0.jpg), 1500x1500 PNG
- Davesprite: [`_10.jpg`](http://f4.bcbits.com/img/a0714927083_10.jpg), 750x750 JPEG; [`_0.jpg`](http://f4.bcbits.com/img/a0714927083_0.jpg), another 750x750 JPEG, but with lighter compression
- Kingside Castle: [`_10.jpg`](http://f4.bcbits.com/img/a0456282355_10.jpg), 1200x1200 JPEG; [`_0.jpg`](http://f4.bcbits.com/img/a0456282355_0.jpg), 1800x1800 JPEG

Again, note that changing `_0.jpg` to `_0.png` does not turn JPEG examples into PNG images. Your file browser, photo viewer, or browser tab or save mechanic can generally help identify if it's actually a JPEG or PNG. But the JPEG files served at `_0.jpg` are still generally better quality than what Bandcamp automatically compresses and downscales for `_10.jpg`, so it's still a worthwhile effort.

**Comment by Niklink** [comment]
Ah, I see what the issue is, now. I was looking at Bandcamp pages archived from 2009-2012, but the current `bcbits` URLs weren't actually put in place until somewhere around mid-2013. For example, the same image was migrated from `http://f0.bcbits.com/z/31/80/3180093346-1.jpg` to `http://f0.bcbits.com/img/a0169239261_2.jpg`.

Secondly it doesn't appear to work in any capacity for banners or backgrounds which is what I was trying to use it for originally, even if it has an updated URL. However it does work for removed tracks! (If they were removed after 2013...) The only use cases for this are currently Indigo Archer and Temporal Shenanigans.

I also discovered a second method for obtaining art URLs: track embeds! Using the format `https://bandcamp.com/EmbeddedPlayer.html/track=[track_id]` you can still call up tracks from hidden albums. After playing the song, the track art will be loaded in! You can also call up album embeds although there is no use case I can think of for this project. Note that THIS method doesn't work with removed tracks, so no Temporal Shenanigans or old Bolin tracks. It's also currently unknown whether bonus tracks have track_ids.

This method specifically allows us to call up tracks from the separate Vols. 1-4 that were hidden with the release of the compilation album in 2011! Also, it probably helps circumvent those awful archive.org loading times. You can find most `track_id`s in the TUHC Asset Pack under `archive\data\music.json`, although for the Vols. 1-4 tracks it omits them in favor of the compilation album's ids.

- [x] Sburban Jungle (Brief Mix)
- [x] Indigo Archer
- [x] Temporal Shenanigans
- [x] Freshjamz tracks
    - Showtime Remix
    - Aggrieve Remix
    - Verdancy (Bassline)
    - Ohgodwhat
    - Ohgodwhat Remix
    - Rediscover Fusion
    - Explore Remix
- [ ] Bonus tracks
    - Aggrieve (Violin Redux)
    - The Thirteenth Hour
    - Theme
    - Walls Covered in Blood DX
    - Trollcops (Radio Play)
    - Catapult Capuchin
    - Science Seahorse
    - A Fairy Battle
    - The Blind Prophet
    - AlterniaBound
    - You Won A Combat
    - Rest A While
    - Maplehoof's Adventure
    - Sburban Reversal
    - White Host, Green Room
    - Vagabounce Remix
    - Tomahawk Head
    - Doctor (Original Loop)
    - How Do I Live (D8 Night Version)
    - Cascade (Beta)
    - Carefree Action
    - null
    - Another Countdown
    - Frustracean
- [ ] Bolin tracks
    - Skaian Dreams (Remix)
    - Guardian
    - Nightlife (Extended) [Vol. 2]
    - Kinetic Verdancy
    - Rediscover Fusion Remix
    - Nightlife (Extended) [MC:DD]
    - Mutiny
    - Guardian V2
    - Contention

Note that a fair amount of these artworks could potentially be reproduced in high quality, being stills from the comic or simple, flat designs.

Also as for the rest of Fandom and Beyond, rest assured that everything under the latest update already uses uncompressed source quality art files.

**Comment by Niklink** [comment]
I've been looking into bonus tracks so far, without success. It IS possible to obtain the `track_id`s of bonus tracks from albums that you own, through the use of streaming on your Bandcamp collection page. However, attempting to plug a bonus track into the Bandcamp track embedder does not work. If you'd like to try this for yourself, the id for Daughter (PX Tone), a bonus track from Desynced Vol. 1, is `2450233549`. The Bandcamp collection page player by itself does not seem to load track arts. I don't know if there's a way to generate `art_id`s from `track_id`s (although I did find a `currentTrack().artURL` method used to load the album artwork on the collection page streamer), and I don't have the technical know-how to poke further.

**Comment by towerofnix** [comment]
Here's a possibly relevant function, mostly in showing an example of the arguments `ImageUtils.artURL` expects:

```js
_track_art_url: function(t, e) {
    let i = null;
    null != t && (i = (n = this._playerdata.tracks[t]) && n.art_id);
    if (!i) {
        var n = this._playlist.get_track();
        i = this._playerdata.album_art_id || this._playerdata.tracks[n].art_id
    }
    const s = function(t, e) {
        const i = [];
        for (var n = 0; n < TemplGlobals.image_formats.length; n++) {
            const t = TemplGlobals.image_formats[n];
            "thumb" == t.resize_algo && t.height == t.width && (e && t.anim_ok || !e && !t.anim_ok) && i.push(t)
        }
        i.sort((function(t, e) {
            return t.width - e.width
        })),
        e && (t *= 2);
        for (n = 0; n < i.length; n++)
            if (i[n].width >= t)
                return i[n].name;
        return i[i.length - 1].name
    }(e, this._params.anim_ok);
    return ImageUtils.artURL(i, s)
}
```

Another call:

```js
art_url: function(t, e) {
    return ImageUtils.artURL(t, e, Templ.current_context.resolve("is_https"))
},
```

And the definition for `ImageUtils.artURL`, formatted for legibility:

```js
imageURL: function(t, i, n) {
    return e("", t, i, n)
},
artURL: function(t, i, n) {
    return e("a", t, i, n)
},

// ...

function e(e, n, s, o) {
    if (!n)
        return TemplGlobals.static_siteroot + "/img/blank.gif";
    s = i(s);
    const r = ImageUtils.imageRoot(o); // https://f4.bcbits.com
  
    let a = s.anim_ok
      ? ""
      : s.file_format && (
        "original" != s.file_format
          ? "." + t[s.file_format]
          : "";

    return (r
      + "/img/"
      + e
      + (n = ("000000000" + n).slice(-10))
      + "_" + s.id + a);
}
```

I'll detangle this a bit further in a follow-up comment.

**Comment by towerofnix** [comment]
By the way, a neat variable for research: `TemplGlobals.image_formats`

The index corresponds to the URL suffix, i.e. index 0 is `_0.jpg` / `_0.png`.

```
 (0) {"resize_algo":"original","file_format":null,"name":"original","id":0}
 (1) {"resize_algo":"scrub","file_format":"original","name":"fullsize","id":1}
 (2) {"resize_algo":"thumb","file_format":"JPEG","width":350,"height":350,"name":"art_thumb","id":2}
 (3) {"resize_algo":"thumb","file_format":"JPEG","width":100,"height":100,"name":"art_thumbthumb","id":3}
 (4) {"resize_algo":"thumb","file_format":"JPEG","width":300,"height":300,"name":"art_embedded_metadata","id":4}
 (5) {"resize_algo":"thumb","file_format":"JPEG","width":700,"height":700,"name":"art_embedded_metadata_large","id":5}
 (6) {"resize_algo":"thumb","file_format":"JPEG","width":100,"height":100,"name":"art_embedded_player","id":6}
 (7) {"resize_algo":"thumb","file_format":"JPEG","width":150,"height":150,"name":"art_embedded_player_large","id":7}
 (8) {"resize_algo":"thumb","file_format":"JPEG","width":124,"height":124,"name":"art_tags","id":8}
 (9) {"resize_algo":"thumb","file_format":"JPEG","width":210,"height":210,"name":"art_tags_large","id":9}
(10) {"resize_algo":"fit","file_format":"JPEG","width":1200,"height":1200,"name":"screen","id":10}
(11) {"resize_algo":"thumb","file_format":"JPEG","width":172,"height":172,"name":"art_tag_search","id":11}
(12) {"resize_algo":"thumb","file_format":"JPEG","width":138,"height":138,"name":"art_artist_index","id":12}
(13) {"resize_algo":"thumb","file_format":"JPEG","width":380,"height":380,"name":"art_solo_feature","id":13}
(14) {"resize_algo":"thumb","file_format":"JPEG","width":368,"height":368,"name":"art_feature","id":14}
(15) {"resize_algo":"thumb","file_format":"JPEG","width":135,"height":135,"name":"art_feed_new_release","id":15}
(16) {"resize_algo":"thumb","file_format":"JPEG","width":700,"quality":70,"minsize":{"format":5,"size":30000},"height":700,"name":"art_app_large","id":16}
(17) {"resize_algo":"fit","file_format":"JPEG","width":1024,"height":1024,"name":"bio_screen","id":20}
(18) {"resize_algo":"fit","file_format":"JPEG","width":120,"height":180,"name":"bio_thumb","id":21}
(19) {"resize_algo":"thumb","file_format":"JPEG","width":25,"height":25,"name":"bio_navbar","id":22}
(20) {"resize_algo":"fit","file_format":"JPEG","width":300,"height":300,"name":"bio_phone","id":23}
(21) {"resize_algo":"thumb","file_format":"JPEG","width":300,"height":300,"name":"bio_licensing","id":24}
(22) {"resize_algo":"fit","file_format":"JPEG","width":700,"quality":70,"height":700,"name":"bio_app","id":25}
(23) {"resize_algo":"thumb","file_format":"JPEG","width":800,"height":600,"name":"bio_subscribe","id":26}
(24) {"resize_algo":"thumb","file_format":"JPEG","width":715,"height":402,"name":"bio_subscribe2","id":27}
(25) {"resize_algo":"thumb","file_format":"JPEG","width":768,"height":432,"name":"bio_featured","id":28}
(26) {"resize_algo":"thumb","file_format":"JPEG","width":100,"height":75,"name":"bio_autocomplete","id":29}
(27) {"resize_algo":"fit","file_format":"original","width":1024,"height":1024,"name":"package_screen","id":31}
(28) {"resize_algo":"thumb","file_format":"JPEG","width":380,"height":285,"name":"package_solo_feature","id":32}
(29) {"resize_algo":"thumb","file_format":"JPEG","width":368,"height":276,"name":"package_feature","id":33}
(30) {"resize_algo":"thumb","file_format":"JPEG","width":400,"height":300,"name":"package_page","id":36}
(31) {"resize_algo":"thumb","file_format":"JPEG","width":168,"height":126,"name":"package_thumb","id":37}
(32) {"resize_algo":"thumb","file_format":"JPEG","width":144,"height":108,"name":"package_thumb_small","id":38}
(33) {"resize_algo":"thumb","file_format":"JPEG","width":210,"height":210,"name":"fan_bio_thumb","id":41}
(34) {"resize_algo":"thumb","file_format":"JPEG","width":50,"height":50,"name":"fan_bio_thumb_small","id":42}
(35) {"resize_algo":"fit","file_format":"JPEG","width":99999,"height":100,"name":"fan_banner","id":43}
(36) {"resize_algo":"fit","file_format":"JPEG","width":99999,"height":200,"name":"fan_banner_2x","id":44}
(37) {"resize_algo":"thumb","file_format":"JPEG","width":140,"height":140,"name":"results_grid","id":50}
(38) {"resize_algo":"thumb","anim_ok":true,"file_format":"JPEG","width":700,"quality":70,"minsize":{"format":69,"size":30000},"height":700,"name":"tralbum_page_cover_art","id":65}
(39) {"resize_algo":"fit","anim_ok":true,"file_format":"JPEG","width":1200,"height":1200,"name":"tralbum_page_cover_art_popup","id":66}
(40) {"resize_algo":"thumb","anim_ok":true,"file_format":"JPEG","width":350,"height":350,"name":"art_thumb_anim_ok","id":67}
(41) {"resize_algo":"thumb","anim_ok":true,"file_format":"JPEG","width":210,"height":210,"name":"art_tags_large_anim_ok","id":68}
(42) {"resize_algo":"thumb","anim_ok":true,"file_format":"JPEG","width":700,"height":700,"name":"art_embedded_metadata_large_anim_ok","id":69}
(43) {"resize_algo":"fit","mozjpeg":true,"file_format":"JPEG","width":360,"height":270,"name":"tralbum_page_package_small","id":70}
(44) {"resize_algo":"fit","mozjpeg":true,"file_format":"JPEG","width":720,"height":540,"name":"tralbum_page_package_large","id":71}
(45) {"resize_algo":"thumb","file_format":"original","width":975,"max_height":180,"name":"custom_header_desktop","id":100,"allow_transparency":true}
(46) {"resize_algo":"fit","file_format":"JPEG","width":750,"height":90,"name":"custom_header_paypal","id":101}
(47) {"resize_algo":"thumb","file_format":"JPEG","width":640,"max_height":124,"name":"custom_header_phone","id":120}
(48) {"resize_algo":"scrub","file_format":"JPEG","name":"design_background","id":130}
(49) {"resize_algo":"thumb","file_format":"JPEG","width":60,"height":45,"name":"subscribe_message","id":140}
(50) {"resize_algo":"thumb","file_format":"JPEG","width":1280,"height":720,"name":"video_landscape","id":150}
(51) {"resize_algo":"thumb","file_format":"JPEG","width":720,"height":1280,"name":"video_portrait","id":151}
(52) {"resize_algo":"thumb_crop","top":0,"file_format":"JPEG","width":60,"left":40,"height":100,"name":"buy_full_email_thumb_montage","id":160}
(53) {"resize_algo":"thumb_crop","top":0,"file_format":"JPEG","width":40,"quality":100,"left":40,"height":80,"name":"buy_full_email_thumb_montage_release","id":161}
(54) {"resize_algo":"thumb_composite","overlay_image":"public/img/banner_email.png","file_format":"JPEG","width":210,"quality":100,"x_offset":92,"y_offset":0,"height":210,"name":"ppp_email_gift_thumb","id":165}
(55) {"resize_algo":"fit","file_format":"JPEG","width":750,"height":422,"name":"weekly_mobile_web","id":170}
(56) {"resize_algo":"fit","file_format":"JPEG","width":1244,"height":646,"name":"weekly_desktop","id":171}
(57) {"resize_algo":"fit","anim_ok":true,"file_format":"JPEG","width":1244,"height":646,"name":"bcdaily_homepage_big","id":180}
(58) {"resize_algo":"fit","file_format":"JPEG","width":1125,"height":420,"name":"mobile_fan_banner_ios_3x","id":200}
(59) {"resize_algo":"fit","file_format":"JPEG","width":750,"height":280,"name":"mobile_fan_banner_ios_2x","id":201}
(60) {"resize_algo":"fit","file_format":"JPEG","width":375,"height":140,"name":"mobile_fan_banner_ios_1x","id":202}
(61) {"resize_algo":"fit","file_format":"JPEG","width":1125,"height":420,"name":"mobile_fan_banner_android_xxxhdpi","id":203}
(62) {"resize_algo":"fit","file_format":"JPEG","width":960,"height":360,"name":"mobile_fan_banner_android_xxhdpi","id":204}
(63) {"resize_algo":"fit","file_format":"JPEG","width":640,"height":240,"name":"mobile_fan_banner_android_xhdpi","id":205}
(64) {"resize_algo":"fit","file_format":"JPEG","width":480,"height":180,"name":"mobile_fan_banner_android_hdpi","id":206}
(65) {"resize_algo":"fit","file_format":"JPEG","width":320,"height":120,"name":"mobile_fan_banner_android_mdpi","id":207}
(66) {"resize_algo":"thumb","file_format":"JPEG","width":900,"height":468,"name":"newsletter_artist_feature","id":220}
(67) {"resize_algo":"thumb","file_format":"JPEG","width":350,"height":350,"name":"grayscale_thumb","filter":"grayscale","id":300}
```

Tasty!

**Comment by towerofnix** [comment]
Here's the code earlier-pasted code detangled and lightly commentated:

```js
function trackArtURL(trackIndex, minWidth) {
  let track;

  let artID = null;

  if (trackIndex)
    artID = this._playerdata.tracks[trackIndex].art_id;

  if (!artID)
    i =
      this._playerdata.album_art_id ||
      this._playerdata.tracks[this._playlist.get_track()].art_id;

  const formats = TemplGlobals.image_formats
    .filter(fmt => fmt.resize_algo == "thumb")
    .filter(fmt => fmt.height == fmt.width)
    .filter(fmt => (
       this._params.anim_ok &&  fmt.anim_ok ||
      !this._params.anim_ok && !fmt.anim_ok
    ));

  formats.sort((a, b) => a.width - b.width);

  if (this._params.anim_ok)
    minWidth *= 2;

  const format =
    formats.find(fmt => fmt.width >= minWidth) ??
    formats[formats.length - 1].name;

  return ImageUtils.artURL(artID, format);
}

function artURL(artID, format) {
  const prefix = "a";

  if (!artID)
    return TemplGlobals.static_siteroot + "/img/blank.gif";

  format = getImageFormat(format);

  const r = ImageUtils.imageRoot(true); // https://f4.bcbits.com

  const formatToExtension = {
    JPEG: "jpg",
    PNG: "png"
  };

  let extension = format.anim_ok
    ? ""
    : format.file_format && (
      "original" != format.file_format
        ? "." + formatToExtension[format.file_format]
        : "";

  return (r
    + "/img/"
    + prefix
    + ("000000000" + artID).slice(-10)
    + "_" + format.id + extension);
}

function getImageFormat(input) {
  if (typeof input == "object")
    return input;

  return TemplGlobals.image_formats // see above comment
    .find(fmt => fmt.id == input || fmt.name == input);
}
```

As for getting the art ID from a track, all `_playerdata` is defined in the embed page HTML itself - look for `<script src=" ... embedded_player-(uuid).js">` and check that element's `data-player-data` property.

Example excerpt from https://bandcamp.com/EmbeddedPlayer.html/track=3752305238:

```js
{"linkback":"https://homestuck.bandcamp.com/track/raw-honey",
 "album_id":1510730992,
 "album_art_id":2256472111,
 "tracks":[
   {"art_id":null,"tracknum":0,"file":{...},"id":3752305238,"title":"Raw Honey"}
 ]}
```

**Pull request merged**
